CREATE TABLE IF NOT EXISTS SensorLog (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    sensor VARCHAR(20) NOT NULL,
    sensor_data FLOAT,
    log_time DATETIME NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS EventLog (
    id BIGINT UNIQUE NOT NULL,
    description VARCHAR(50) NOT NULL,

    CONSTRAINT eventlog_id_fkey
    FOREIGN KEY (id)
    REFERENCES SensorLog(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);